defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: rpm_logger_development

test:
  <<: *defaults
  database: rpm_logger_test

production:
  <<: *defaults
  database: rpm_logger
